## AnE CONFIGS
env_name: "MiniGrid-DoorKey-8x8-v0"
rollouts: 50
opt_steps: 10
init_qs: 6
rollout_length : 128 
qs_per_step : 1
alpha : 0.3
lr: 0.003

#PPO specific configs
ppo:
    gamma: 0.99
    lambda: 0.95
    clip_epsilon : 0.2


