## AnE CONFIGS
env_name: "MiniGrid-Playground-v0"
rollouts: 128
opt_steps: 10
init_qs: 20
rollout_length : 20
qs_per_step : 1
alpha : 0.3
lr: 0.001

#PPO specific configs
ppo:
    gamma: 0.99
    lambda: 0.95
    clip_epsilon : 0.2


